server:
  listen_addr: ":9090"

database:
  host: "mysql"
  port: "3306"
  user: "root"
  password: "skynet123"
  db_name: "skynet"

jwt:
  secret: "skynet-dev-secret"

log_level: "debug"

embedding:
  base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  api_key: "sk-6fd6cb2f1ea349b3b77f2931c7cf5814"
  model: "text-embedding-v3"
